quarkus:
  log:
    level: INFO
    category:
      "io.quarkus.rest.client":
        level: DEBUG
      "pe.com.relari":
        level: DEBUG
      "org.apache.http":
        level: TRACE
  rest-client:
    logging:
      scope: request-response
      body-limit: 1024
    json-place-holder-api:
      url: https://jsonplaceholder.typicode.com
      scope: jakarta.inject.Singleton
      connect-timeout: 5000
      read-timeout: 5000
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
      username: sa
      password: ""
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
    sql-format: true

  dev-ui:
    enabled: true

greeting:
  message: Hello World

application:
  version: 1.0.0
  name: Quarkus Application
  errors:
    default-message: Generic error message
    status: 500
    code: MV
    categories:
      MOVIE_NOT_FOUND:
        code: 'MV001'
        description: 'Movie not found.'
        status: 404
      MOVIE_SAVE_FAILED:
        code: 'MV002'
        description: 'Error saving the movie.'
        status: 500
      MOVIE_UPDATE_FAILED:
        code: 'MV003'
        description: 'Error updating the movie.'
        status: 500
      MOVIE_NOT_INACTIVATED:
        code: 'EM004'
        description: 'Movie no inactivado.'
        status: 409
      MOVIE_NOT_ACTIVATED:
        code: 'EM005'
        description: 'Movie no activado.'
        status: 409
