quarkus:
  application:
    name: api-neg-movies
    version: '@project.version@'
  banner:
    path: banner.txt
  jackson:
    serialization-inclusion: non-null
  http:
    root-path: /api/neg/v1
#    port: 8092

  smallrye-openapi:
    path: ${quarkus.http.root-path}/q/openapi
  smallrye-health:
    path: ${quarkus.http.root-path}/q/health
